# Generated by Django 4.2 on 2025-01-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('apprenant', 'Apprenant'), ('employeur', 'Employeur'), ('formateur', 'Formateur')], default='Apprenant', max_length=10),
        ),
    ]
