# Generated by Django 4.2 on 2025-02-07 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil_formateur',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Domaine_expertise', models.CharField(default='', max_length=200)),
                ('fonction', models.CharField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.customuser',),
        ),
    ]
