# Generated by Django 4.2 on 2025-02-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profil_formateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Domaine_expertise',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fonction',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Profil_formateur',
        ),
    ]
