# Generated by Django 4.2 on 2025-02-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_domaine_expertise_customuser_fonction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Domaine_expertise',
            new_name='domaine_expertise',
        ),
    ]
