# Generated by Django 4.2 on 2025-02-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_domaine_expertise_customuser_domaine_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='domaine_expertise',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fonction',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
