# Generated by Django 4.2 on 2025-02-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_domaine_expertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='domaine_expertise',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fonction',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
