# Generated by Django 4.2 on 2025-02-10 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_customuser_domaine_expertise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='domaine_expertise',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fonction',
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('domaine_expertise', models.CharField(default='null', max_length=20)),
                ('fonction', models.CharField(default='null', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.customuser',),
        ),
    ]
