# Generated by Django 4.2 on 2025-02-10 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_customuser_domaine_expertise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formateur',
            name='customuser_ptr',
        ),
        migrations.AddField(
            model_name='formateur',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
