# Generated by Django 4.2 on 2025-02-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '__first__'),
        ('users', '0020_remove_formateur_customuser_ptr_formateur_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formateur',
            new_name='Encadrant',
        ),
    ]
