# Generated by Django 4.2 on 2025-02-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_formateur_encadrant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Encadrant',
        ),
    ]
