# Generated by Django 4.2.15 on 2025-01-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offres', '0011_offerapplication_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='application_link',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='application_mode',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='can_add_others_doc',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_remote',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_required_cv_doc',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_required_ml_doc',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='online_submission',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='physical_address',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='posted_date',
        ),
        migrations.AddField(
            model_name='offer',
            name='additionalInfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='applicationLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='applicationMode',
            field=models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical'), ('Both', 'Both')], default='Online', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='canAddOthersDoc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='contactEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='contractType',
            field=models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('Internship', 'Internship'), ('Freelance', 'Freelance'), ('Temporary', 'Temporary')], default='CDD', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='educationLevel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='enterWebsite',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='enterpriseLocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='experienceLevel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='expirationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='isRemote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='isRequiredCvDoc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='isRequiredMlDoc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='onlineSubmission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='postedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='domain',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
