# Generated by Django 4.2.15 on 2025-01-20 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Offres', '0012_remove_offer_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Offre', 'verbose_name_plural': 'Offres'},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='updatedDate',
        ),
        migrations.AddField(
            model_name='offer',
            name='benefits',
            field=models.TextField(blank=True, null=True, verbose_name='Avantages'),
        ),
        migrations.AddField(
            model_name='offer',
            name='createdBy',
            field=models.ForeignKey(default='16', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='offer',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='additionalInfo',
            field=models.TextField(blank=True, null=True, verbose_name='Informations supplémentaires'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='applicationLink',
            field=models.URLField(blank=True, null=True, verbose_name='Lien de candidature'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='applicationMode',
            field=models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical'), ('Both', 'Both')], default='Online', max_length=10, verbose_name='Mode de candidature'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='canAddOthersDoc',
            field=models.BooleanField(default=False, verbose_name='Autres documents autorisés'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contactEmail',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email de contact'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contractType',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD')], default='CDD', max_length=3, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(null=True, verbose_name="Description de l'offre"),
        ),
        migrations.AlterField(
            model_name='offer',
            name='domain',
            field=models.CharField(max_length=255, null=True, verbose_name="Domaine de l'offre"),
        ),
        migrations.AlterField(
            model_name='offer',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée (en mois)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='educationLevel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Niveau d'éducation requis"),
        ),
        migrations.AlterField(
            model_name='offer',
            name='enterWebsite',
            field=models.URLField(blank=True, null=True, verbose_name="Site web de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='offer',
            name='enterprise',
            field=models.CharField(max_length=255, verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='enterpriseLocation',
            field=models.CharField(max_length=255, null=True, verbose_name="Localisation de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='offer',
            name='experienceLevel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Niveau d'expérience requis"),
        ),
        migrations.AlterField(
            model_name='offer',
            name='expirationDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='offer',
            name='isRemote',
            field=models.BooleanField(default=False, verbose_name='Télétravail'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='isRequiredCvDoc',
            field=models.BooleanField(default=True, verbose_name='CV requis'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='isRequiredMlDoc',
            field=models.BooleanField(default=False, verbose_name='Lettre de motivation requise'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name="Localisation de l'offre"),
        ),
        migrations.AlterField(
            model_name='offer',
            name='onlineSubmission',
            field=models.BooleanField(default=True, verbose_name='Soumission en ligne'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='postedDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Exigences'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='responsibilities',
            field=models.TextField(blank=True, null=True, verbose_name='Responsabilités'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Open', max_length=10, verbose_name="Statut de l'offre"),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name="Titre de l'offre"),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('Job', 'Job'), ('Internship', 'Internship'), ('Other', 'Other')], max_length=20, verbose_name="Type d'offre"),
        ),
    ]
