# Generated by Django 4.2 on 2025-02-04 18:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Offres', '0013_alter_offer_options_remove_offer_updateddate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offerapplication',
            unique_together={('offer', 'candidat')},
        ),
    ]
