# Generated by Django 4.2 on 2025-02-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinar',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='webinar',
            old_name='updatedAt',
            new_name='updateDate',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='registrationDeadline',
        ),
    ]
