# Generated by Django 4.2 on 2025-02-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0003_rename__id_webinar_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='startDateTime',
        ),
        migrations.AlterField(
            model_name='webinar',
            name='duree',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='format',
            field=models.CharField(choices=[('FuturAllies', 'Gratuit'), ('Café des allies', 'Payant')], default='Payant', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='isPaid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='maxParticipants',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='type',
            field=models.CharField(choices=[('FuturAllies', 'FuturAllies'), ('Café des allies', 'Café des allies')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='updateDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='webinarUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
