# Generated by Django 4.2 on 2025-02-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0004_remove_webinar_startdatetime_alter_webinar_duree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='startDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='format',
            field=models.CharField(choices=[('FuturAllies', 'Gratuit'), ('Café des allies', 'Payant')], default='Payant', max_length=20),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
