# Generated by Django 4.2 on 2025-02-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0005_webinar_startdatetime_alter_webinar_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='format',
        ),
    ]
